# version of docker-compose tool
version: '3.7'
# services to deploy (containers within image)
services:
  # name of container; name used to other containers to find
  narneso_mongodb_container:
    # specifies docker image, official docker image from docker-hub
    image: mongo:latest
    # variables docker container will use to start up
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # port for mongodb for host: port for the container
    # host port needs explicit declaration with localhost address
    # by default 27107:27107 host is mongodb://127.0.0.1:27107/admin
    # port mapping of '20000:27107' would be incomplete host port
    ports:
      - 127.0.0.1:20000:27017
    # specifies what file locations our container is allowed to interact with
    volumes:
      # volume name inside container: volume name outside of container
      - narneso-data:/data/db

# volumes section
volumes:
  # declaration of 'narenesso-data' var for volumes
  narneso-data:
