# version of docker-compose tool
version: '3.7'
# services to deploy (containers within image)
services:
  # name of container; name used to other containers to find
  narneso_mongodb_container:
    # specifies docker image, official docker image from docker-hub
    image: mongo:latest
    # variables docker container will use to start up
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # port for mongodb for host: port for the container
    # host port needs explicit declaration with localhost address
    # by default 27107:27107 host is mongodb://127.0.0.1:27107/admin
    # port mapping of '20000:27107' would be incomplete host port
    ports:
      - 127.0.0.1:20000:27017
    # specifies what file locations our container is allowed to interact with
    volumes:
      # volume name inside container: volume name outside of container
      - narneso-data:/data/db
    # connect this container explicitly to the network created to manage containers
    networks:
      - dev

  narnesso_seed_data:
    # build and run commands with dockerfile in directory
    build: ./narnesso_seed_data
    # connect this container explicitly to the network created to manage containers
    networks:
      - dev
    # depends_on:
    #   - narneso_mongodb_container

# declare volume names
volumes:
  # declaration of 'narenesso-data' var name for volumes
  narneso-data:

# define networks
networks:
  dev:
    driver: bridge
